import { ShieldCheck, ArrowUpRight, Trash2, GitBranch, Film } from 'lucide-react';
import { Button, Modal } from './ui/primitives';
import { repoUrl } from '../lib/utils';
import { studio, useStudio } from '../app/store';
export function About({ open, onOpenChange }: {
    open: boolean;
    onOpenChange: (v: boolean) => void;
}) {
    const { tasks } = useStudio(), url = repoUrl();
    return <Modal open={open} onOpenChange={onOpenChange} title="A little studio. All yours." description="Creator AutoEdit · Signal Studio edition" wide><div className="about-intro"><div className="about-icon"><ShieldCheck size={26}/></div><div><h3>Your video stays on your device.</h3><p>Editing, recording and transcription happen locally in your browser.</p></div></div><div className="about-grid"><section><span className="eyebrow-small">THE PRIVACY DETAILS</span><p>Creator AutoEdit downloads the processing code and speech models required to edit or rehearse your video, but your source video, audio, transcript and exported video are not uploaded by the application.</p><p>Application files come from this site. Speech-model files come from Hugging Face. Face-model files come from Google’s model hosting. Those hosts receive ordinary asset-download requests, not your footage.</p><p>No account, database, analytics or session replay. Prompt scripts, recording manifests and take chunks are stored locally in IndexedDB so you can return to them on this device. Use the original-download action for important recordings because browser storage can be evicted.</p></section><section><span className="eyebrow-small">INSIDE THE MACHINE</span><div className="architecture-mini mono"><span><Film size={12}/> CAMERA + MIC</span><i>↓</i><span>NATIVE MEDIARECORDER</span><i>↓</i><span>ORDERED LOCAL CHUNKS</span><i>↓</i><span>ONE SHARED EDIT MAP</span><i>↓</i><strong>H.264 + AAC → MP4</strong></div></section></div><section className="about-limitations"><h3>Designed for one voice.</h3><p>English talking-head clips, up to 5 minutes. Under 3 minutes is recommended. Input codecs, output size and speed depend on your browser and hardware. HDR footage needs an SDR copy. Automatic transcripts and framing can need correction. Background music and multiple speakers are outside this version’s focus.</p><p>This source build is a release candidate. See <code>QA_REPORT.md</code> in the repository for the exact verification status; phone and browser compatibility must not be inferred from the interface.</p></section><div className="cache-control"><div><strong>Downloaded speech models</strong><p>Clear cached models without changing this edit. Caption work in progress will stop.</p></div><Button size="small" onClick={() => void studio.clearModels()}><Trash2 size={14}/>{tasks.captions.status === 'running' ? 'Stop & clear' : 'Clear models'}</Button></div><div className="about-source">{url ? <a href={url} target="_blank" rel="noopener noreferrer"><GitBranch size={17}/>Source, architecture & license notices<ArrowUpRight size={15}/></a> : <p>Source code is included with this build. Set <code>VITE_REPOSITORY_URL</code> to your GitHub repository; project-page deployments also infer it from their URL.</p>}<span className="mono">RELEASE CANDIDATE / 0.9</span></div></Modal>;
}
