import { useRef, useState } from 'react';
import { motion, useReducedMotion } from 'motion/react';
import { ArrowRight, ArrowLeft, Check, Download, Share2, ShieldCheck, Scissors, AudioLines, Captions, ScanFace, Film } from 'lucide-react';
import { studio, useStudio } from '../app/store';
import { Brand, RepositoryLink } from './Brand';
import { Alert, Badge, Button, Card } from './ui/primitives';
import { EditMap } from '../features/edit-map';
import { projectCuts } from '../features/silence';
import { saveVideo, shareVideo, canShareVideo } from '../features/sharing';
import { timecode, bytes, isAbort } from '../lib/utils';

export function Exporting() {
    const { project, tasks } = useStudio();
    const last = useRef(0);
    const reduce = useReducedMotion();
    if (!project) return null;
    if (tasks.export.progress !== undefined) last.current = tasks.export.progress;
    const progress = last.current;
    const layers = [{ name: 'VIDEO', icon: Film, on: true }, { name: 'CAPTIONS', icon: Captions, on: project.captions.enabled && project.words.length > 0 }, { name: 'AUDIO', icon: AudioLines, on: project.metadata.hasAudio }, { name: 'CUTS', icon: Scissors, on: project.cutPreset !== 'off' }, { name: 'FRAME', icon: ScanFace, on: true }].filter(layer => layer.on);
    return <div className="export-page"><header className="site-header"><Brand compact /><Badge variant="outline">Exporting on this device</Badge><Button variant="ghost" size="small" onClick={studio.cancel}><ArrowLeft size={15} />Back to edit</Button></header><main className="export-main"><section className="export-story"><span className="eyebrow"><span className="status-light" /> EXPORTING</span><h1>Your edit is<br /><span>becoming an MP4.</span></h1><p>Cutting sound gaps, rendering your frame and preserving the source audio.</p><div className="export-progress-copy"><div><strong>{tasks.export.progress === undefined ? <span className="export-working">Working</span> : <>{Math.floor(tasks.export.progress * 100)}<span>%</span></>}</strong><small className="mono">{tasks.export.progress === undefined ? 'PREPARING FILE' : 'FRAMES RENDERED'}</small></div><div className="export-status" role="status">{tasks.export.detail}</div></div><div className="export-progress-track" role="progressbar" aria-label="Video frames rendered" aria-valuemin={0} aria-valuemax={100} aria-valuenow={tasks.export.progress === undefined ? undefined : Math.round(tasks.export.progress * 100)}><span style={{ width: `${progress * 100}%` }} /></div><p className="export-stay"><ShieldCheck size={16} />Keep this tab open while the file is written.</p></section><Card className="export-stack" aria-label="Editing layers merging into a finished video">{layers.map((layer, index) => <motion.div className="export-layer" key={layer.name} style={{ zIndex: layers.length - index }} animate={{ x: reduce ? 0 : (index - 2) * 21 * (1 - progress), y: reduce ? 0 : (index - 2) * 27 * (1 - progress), rotate: reduce ? 0 : (index - 2) * 3 * (1 - progress), opacity: index === 0 ? 1 : 1 - progress * .88 }} transition={{ type: 'spring', stiffness: 70, damping: 22 }}><div className="layer-title mono"><layer.icon size={13} />{layer.name}<Check size={12} /></div>{index === 0 && <div className="layer-image">{project.source.thumbnail && <img src={project.source.thumbnail} alt="Your video being rendered" />}<span className="layer-file mono">AUTOEDIT.MP4</span></div>}</motion.div>)}<div className="stack-caption mono">LOCAL FILE · NO CLOUD QUEUE</div></Card></main></div>;
}

export function Complete({ onAbout, onNew, onBack }: { onAbout: () => void; onNew: () => void; onBack?: () => void }) {
    const { project, result } = useStudio();
    const [sharing, setSharing] = useState(false);
    if (!project || !result) return null;
    const map = EditMap.fromCuts(project.metadata.duration, projectCuts(project));
    const words = project.captions.enabled ? project.words.filter(word => map.remapWord(word)).length : 0;
    const share = async () => { setSharing(true); try { await shareVideo(result); } catch (error) { if (!isAbort(error)) studio.fail('The video couldn’t be shared', error); } finally { setSharing(false); } };
    return <div className="complete-page"><header className="site-header"><div className="editor-brand">{onBack && <Button variant="ghost" size="small" onClick={onBack}><ArrowLeft size={15} />Back</Button>}<Brand compact onClick={onNew} /></div><RepositoryLink onAbout={onAbout} /></header><main className="complete-main"><section className="complete-copy"><div className="completion-check"><Check size={23} /></div><span className="eyebrow">EXPORT COMPLETE</span><h1>Ready<br /><span>to post.</span></h1><p>Your edit is saved as a playable MP4 with the source display ratio preserved.</p><div className="result-metrics"><div><span>ORIGINAL</span><strong className="mono">{timecode(project.metadata.duration)}</strong></div><div><span>EDITED</span><strong className="mono">{timecode(result.duration)}</strong></div><div><span>REMOVED</span><strong className="mono">{Math.max(0, project.metadata.duration - result.duration).toFixed(1)}s</strong></div><div><span>CAPTIONS</span><strong className="mono">{words}</strong></div></div><div className="complete-actions">{canShareVideo(result) && <Button variant="default" size="large" disabled={sharing} onClick={() => void share()}><Share2 size={18} />Share video<ArrowRight size={17} /></Button>}<Button variant={canShareVideo(result) ? 'secondary' : 'default'} size="large" onClick={() => saveVideo(result)}><Download size={18} />Save video</Button></div><p className="save-hint">On iPhone, use Share → Save Video when available, or save the MP4 to Files.</p><Button variant="ghost" className="edit-again" onClick={studio.editAgain}><ArrowLeft size={14} />Edit again</Button><div className="open-source-note"><span>Free &amp; open source.</span><RepositoryLink onAbout={onAbout} label="Open on GitHub" /></div></section><section className="finished-video"><Card className="result-video-card" style={{ aspectRatio: `${result.width}/${result.height}` }}><video src={result.url} controls playsInline preload="metadata" aria-label="Your finished exported MP4" /></Card><div className="result-file-info"><span><Check size={12} />{result.name}</span><span className="mono">{result.width} × {result.height} · {bytes(result.size)} · MP4</span></div><Alert title="Saved locally">Use Save video or Share video to keep a copy outside this browser session.</Alert></section></main></div>;
}
